import"./assets/scroll-up-2f72e7b4.js";import{a as l,N as L,l as x}from"./assets/vendor-a9f52953.js";l.defaults.headers.post["Content-Type"]="application/json";l.defaults.baseURL="https://books-backend.p.goit.global/";async function B(){return(await l.get("/books/top-books")).data}async function _(e){return(await l.get(`books/category?category=${e}`)).data}async function h(e){return(await l.get(`books/${e}`)).data}document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("authModal"),t=document.getElementById("sign-in-button-main"),o=document.querySelector(".auth-form-close"),s=document.getElementById("signup-link"),c=document.getElementById("signin-link"),M=document.getElementById("signup-form");document.getElementById("signin-form");const g=document.querySelector(".btn-sign-up");t.addEventListener("click",function(){w(e)}),o.addEventListener("click",function(){e.style.display="none"}),s.addEventListener("click",function(a){a.preventDefault(),y("Sign up")}),c.addEventListener("click",function(a){a.preventDefault(),y("Sign in")}),M.addEventListener("submit",function(a){a.preventDefault();const i=document.getElementById("name").value,r=document.getElementById("email").value,b=document.getElementById("password").value,f={name:i,email:r,password:b};$(f),q(f),e.style.display="none",this.reset()});function w(a){a.style.display="block"}function $(a){const i=JSON.parse(localStorage.getItem("users"))||[];i.push(a),localStorage.setItem("users",JSON.stringify(i))}function y(a){g&&(g.textContent=a)}function q(a){const i=document.getElementById("sign-in-button-main");i.style.display="none";const r=document.createElement("div");r.classList.add("user-circle"),r.textContent=a.name.charAt(0).toUpperCase(),document.querySelector(".right-col").appendChild(r)}});const T="https://books-backend.p.goit.global/books/",D="category-list";async function N(){try{const e=await l.get(T+D);if(e.status===200){const t=e.data,o=document.querySelector(".categories-list");t.map(s=>{const c=document.createElement("li");c.textContent=s.list_name,c.classList.add("categ-item"),o.appendChild(c)})}else L.Notify.failure(`Request execution error. Status code: ${e.status}`)}catch(e){L.Notify.failure("An error occurred while sending the request."),console.error("An error occurred while sending the request:",e)}}N();const u=document.querySelector(".books"),d=document.querySelector(".categories-list"),j=document.querySelector("#books-category-name");A();async function A(){const e=await B(),t=E(e);u.insertAdjacentHTML("beforeend",t)}function E(e){return e.map(t=>I(t.list_name,t.books,!1))}function I(e,t,o){let s=o?"":`<div class = "books-list-name" >${e}</div>`;s+=`<ul class="books-container ${o?"books-container-multi":""}">
                    ${H(t)}
                </ul>`;const c=o?"":`<button class = "books-btn" type = "button" id="${e}"> SEE MORE </button>`;return s+=c,s}function H(e){return e.map(t=>`<li>
                <div data-book=${t._id} class="book-block">
                    <img src="${t.book_image}" class="book-pic" width=120 heigh=240 />
                    <p class="book-name">${t.title}</p>
                    <p class="book-author">${t.author}</p>
                </div>
         </li>`).join("")}d.addEventListener("click",async e=>{if(e.preventDefault(),e.target==d)return;const t=e.target.innerHTML;S(t)});async function S(e){for(const o of d.children)o.innerHTML!=e?o.classList.remove("is-active-item"):o.classList.add("is-active-item");let t=null;if(e=="All categories"){v("Best Sellers Books");const o=await B();t=E(o)}else{v(e);const o=await _(e);t=I(e,o,!0)}u.innerHTML=t,window.scrollTo({top:0,behavior:"smooth"})}function v(e){const t=e.split(" ");j.innerHTML=`<span class="dark-text">${t[0]}</span> ${t.slice(1).join(" ")}`}u.addEventListener("click",async e=>{if(e.target.classList.contains("books-btn")){const t=e.target.id;S(t)}});const n={coverModal:document.querySelector(".cover-modal"),modalCoverContent:document.querySelector(".modal-cover-content"),closeBtn:document.querySelector(".modal-btn-close"),body:document.querySelector("body"),addBtn:document.querySelector(".add"),removeBtn:document.querySelector(".remove"),openListBtn:document.querySelector(".open-list"),modalText:document.querySelector(".modal-add-text"),booksListElement:document.querySelector(".books")};n.booksListElement.addEventListener("click",e=>{let t=null;if(e.target.classList.contains("book-block"))t=e.target.dataset.book;else if(e.target.parentNode.classList.contains("book-block"))t=e.target.parentNode.dataset.book;else return;O(t)});async function O(e){try{const t=await h(e);n.modalCoverContent.dataset.selectedBookId=t._id,U(t),J(),k(t._id)}catch(t){console.log(t)}}n.removeBtn.addEventListener("click",()=>{const e=n.modalCoverContent.dataset.selectedBookId;e&&z(e)});n.addBtn.addEventListener("click",async()=>{const e=n.modalCoverContent.dataset.selectedBookId;if(e){const t=await h(e);R(t)}});function U(e){const t=`
                <img src="${e.book_image}" alt="book cover" class="modal-img">

                <div class="modal-contant-box">
                    <h2 class="modal-title">${e.title}</h2>
                    <h3 class="modal-book-author">${e.author}</h3>
                    <p class="modal-text">${e.description}</p>
                    <ul class="modal-list">
                        ${F(e.buy_links)}
                    </ul>
                </div>`;n.modalCoverContent.innerHTML=t}function F(e){return e.map(t=>{let o=null;switch(t.name){case"Amazon":{o="../images/amazon_logo.jpg";break}case"Apple Books":{o="../images/apple_books.jpg";break}default:o="../images/book.jpg"}return`<li class="modal-item">
              <a href="${t.url}" target="_blank" rel="noopener noreferrer nofollow" class="modal-link">
              <img src=${o} alt=${t.name} class="modal-icon amazone-js"></a>
    </li>`}).join("")}function J(){n.coverModal.classList.add("visible-element"),n.body.classList.add("no-scroll"),document.addEventListener("keydown",x.throttle(m,500))}n.coverModal.addEventListener("click",e=>{(e.target.classList.contains("cover-modal")||e.target.classList.contains("modal-btn-close"))&&(n.coverModal.classList.remove("visible-element"),n.body.classList.remove("no-scroll"),document.removeEventListener("keydown",m))});function m(e){e.key==="Escape"&&(n.coverModal.classList.remove("visible-element"),document.removeEventListener("keydown",m))}function R(e){console.log(e);const t=p(),o=t.some(s=>s._id===e._id);console.log(t),o||(t.push(e),console.log(t),C(t)),k(e._id)}function p(){return JSON.parse(localStorage.getItem("booksInList"))??[]}function C(e){localStorage.setItem("booksInList",JSON.stringify(e))}function k(e){p().some(s=>s._id===e)?(n.addBtn.style.display="none",n.removeBtn.style.display="block",n.modalText.style.display="block"):(n.addBtn.style.display="block",n.removeBtn.style.display="none",n.modalText.style.display="none")}function z(e){const o=p().filter(s=>s._id!==e);C(o),k(e)}
//# sourceMappingURL=commonHelpers.js.map
