import"./assets/scroll-up-7077472c.js";import{a as i,N as g}from"./assets/vendor-77e6b4aa.js";i.defaults.headers.post["Content-Type"]="application/json";i.defaults.baseURL="https://books-backend.p.goit.global/";async function y(){return(await i.get("/books/top-books")).data}async function M(t){return(await i.get(`books/category?category=${t}`)).data}document.addEventListener("DOMContentLoaded",function(){const t=document.getElementById("authModal"),e=document.getElementById("sign-in-button-main"),n=document.querySelector(".auth-form-close"),s=document.getElementById("signup-link"),a=document.getElementById("signin-link"),r=document.getElementById("signup-form"),d=document.getElementById("signin-form"),p=document.querySelector(".btn-sign-up");e.addEventListener("click",function(){L(t)}),n.addEventListener("click",function(){t.style.display="none"}),s.addEventListener("click",function(o){o.preventDefault(),m("Sign up"),r.style.display="block",d.style.display="none"}),a.addEventListener("click",function(o){o.preventDefault(),m("Sign in"),d.style.display="block",r.style.display="none"}),r.addEventListener("submit",function(o){o.preventDefault();const c=document.getElementById("name").value,E=document.getElementById("email").value,B=document.getElementById("password").value;v({name:c,email:E,password:B}),t.style.display="none",this.reset()});function L(o){o.style.display="block"}function v(o){const c=JSON.parse(localStorage.getItem("users"))||[];c.push(o),localStorage.setItem("users",JSON.stringify(c))}function m(o){p&&(p.textContent=o)}});const S="https://books-backend.p.goit.global/books/",w="category-list";async function $(){try{const t=await i.get(S+w);if(t.status===200){const e=t.data,n=document.querySelector(".categories-list");e.map(s=>{const a=document.createElement("li");a.textContent=s.list_name,a.classList.add("categ-item"),n.appendChild(a)})}else g.Notify.failure(`Request execution error. Status code: ${t.status}`)}catch(t){g.Notify.failure("An error occurred while sending the request."),console.error("An error occurred while sending the request:",t)}}$();const u=document.querySelector(".books"),l=document.querySelector(".categories-list"),I=document.querySelector("#books-category-name");q();async function q(){const t=await y(),e=f(t);u.insertAdjacentHTML("beforeend",e)}function f(t){return t.map(e=>b(e.list_name,e.books,!1))}function b(t,e,n){let s=n?"":`<div class = "books-list-name" >${t}</div>`;s+=`<ul class="books-container ${n?"books-container-multi":""}">
                    ${D(e)}
                </ul>`;const a=n?"":`<button class = "books-btn" type = "button" id="${t}"> SEE MORE </button>`;return s+=a,s}function D(t){return t.map(e=>`<li>
                <div data-book=${e._id} class="book-block">
                    <img src="${e.book_image}" class="book-pic" width=120 heigh=240 />
                    <p class="book-name">${e.title}</p>
                    <p class="book-author">${e.author}</p>
                </div>
         </li>`).join("")}l.addEventListener("click",async t=>{if(t.preventDefault(),t.target==l)return;const e=t.target.innerHTML;h(e)});async function h(t){for(const n of l.children)n.innerHTML!=t?n.classList.remove("is-active-item"):n.classList.add("is-active-item");let e=null;if(t=="All categories"){k("Best Sellers Books");const n=await y();e=f(n)}else{k(t);const n=await M(t);e=b(t,n,!0)}u.innerHTML=e,window.scrollTo({top:0,behavior:"smooth"})}function k(t){const e=t.split(" ");I.innerHTML=`<span class="dark-text">${e[0]}</span> ${e.slice(1).join(" ")}`}u.addEventListener("click",async t=>{if(t.target.classList.contains("books-btn")){console.log("here");const e=t.target.id;h(e)}});
//# sourceMappingURL=commonHelpers.js.map
