import"./assets/scroll-up-8775bb2b.js";import{a,l as v}from"./assets/vendor-27bc9ff5.js";a.defaults.headers.post["Content-Type"]="application/json";a.defaults.baseURL="https://books-backend.p.goit.global/";async function b(){return(await a.get("/books/top-books")).data}async function h(o){return(await a.get(`books/category?category=${o}`)).data}async function p(o){return(await a.get(`books/${o}`)).data}const B="https://books-backend.p.goit.global/books/",w="category-list";async function I(){try{const o=await a.get(B+w);if(o.status===200){const e=o.data,t=document.querySelector(".categories-list");e.map(n=>{const c=document.createElement("li");c.textContent=n.list_name,c.classList.add("categ-item"),t.appendChild(c)})}else Notiflix.Notify.failure(`Request execution error. Status code: ${o.status}`)}catch(o){Notiflix.Notify.failure("An error occurred while sending the request."),console.error("An error occurred while sending the request:",o)}}I();const r=document.querySelector(".books"),l=document.querySelector(".categories-list"),S=document.querySelector("#books-category-name"),i=document.querySelector(".modal-loading");$();async function $(){i.classList.remove("hidden");const o=await b(),e=g(o);r.insertAdjacentHTML("beforeend",e),i.classList.add("hidden")}function g(o){return o.map(e=>y(e.list_name,e.books,!1))}function y(o,e,t){let n=t?"":`
    <div class = "books-list-name" >${o}</div>`;n+=`<ul class="books-container ${t?"books-container-multi":""}">
                    ${M(e)}
                </ul>`;const c=t?"":`<button class = "books-btn" type = "button" id="${o}"> SEE MORE </button>`;return n+=c,n}function M(o){return o.map(e=>`<li class="book-block-two">
                <div data-book=${e._id} class="book-block">
                    <img src="${e.book_image}" class="book-pic" width=120 heigh=240 />
                    <p class="book-name">${e.title}</p>
                    <p class="book-author">${e.author}</p>
                </div>
         </li>`).join("")}l.addEventListener("click",async o=>{if(o.preventDefault(),o.target==l)return;const e=o.target.innerHTML;f(e)});async function f(o){i.classList.remove("hidden");for(const t of l.children)t.innerHTML!=o?t.classList.remove("is-active-item"):t.classList.add("is-active-item");let e=null;if(o=="All categories"){k("Best Sellers Books");const t=await b();e=g(t)}else{k(o);const t=await h(o);e=y(o,t,!0)}r.innerHTML=e,i.classList.add("hidden"),window.scrollTo({top:0,behavior:"smooth"})}function k(o){const e=o.split(" ");S.innerHTML=`<span class="dark-text">${e[0]}</span> ${e.slice(1).join(" ")}`}r.addEventListener("click",async o=>{if(o.target.classList.contains("books-btn")){const e=o.target.id;f(e)}});const s={coverModal:document.querySelector(".cover-modal"),modalCoverContent:document.querySelector(".modal-cover-content"),closeBtn:document.querySelector(".modal-btn-close"),body:document.querySelector("body"),addBtn:document.querySelector(".add"),removeBtn:document.querySelector(".remove"),openListBtn:document.querySelector(".open-list"),modalText:document.querySelector(".modal-add-text"),booksListElement:document.querySelector(".books"),body:document.querySelector("body")};s.booksListElement.addEventListener("click",o=>{let e=null;if(o.target.classList.contains("book-block"))e=o.target.dataset.book;else if(o.target.parentNode.classList.contains("book-block"))e=o.target.parentNode.dataset.book;else return;_(e)});async function _(o){try{const e=await p(o);s.modalCoverContent.dataset.selectedBookId=e._id,q(e),C(),m(e._id)}catch(e){console.log(e)}}s.removeBtn.addEventListener("click",()=>{const o=s.modalCoverContent.dataset.selectedBookId;o&&T(o)});s.addBtn.addEventListener("click",async()=>{const o=s.modalCoverContent.dataset.selectedBookId;if(o){const e=await p(o);x(e)}});function q(o){const e=`
                <img src="${o.book_image}" alt="book cover" class="modal-img">

                <div class="modal-contant-box">
                    <h2 class="modal-title">${o.title}</h2>
                    <h3 class="modal-book-author">${o.author}</h3>
                    <p class="modal-text">${o.description}</p>
                    <ul class="modal-list">
                        ${E(o.buy_links)}
                    </ul>
                </div>`;s.modalCoverContent.innerHTML=e}function E(o){return o.map(e=>{let t=null;if(s.body.classList.contains("dark-theme"))switch(e.name){case"Amazon":{t="./images/amazon_logo.svg";break}case"Apple Books":{t="./images/apple_books.svg";break}default:return""}else switch(e.name){case"Amazon":{t="./images/amazon_logo.svg";break}case"Apple Books":{t="./images/apple_books.svg";break}default:return""}return`<li class="modal-item">

              <a href="${e.url}" target="_blank" rel="noopener noreferrer nofollow" class="modal-link">
              <img src=${t} alt=${e.name} class="modal-icon amazone-js"></a>
    </li>`}).join("")}function C(){s.coverModal.classList.add("visible-element"),s.body.classList.add("no-scroll"),document.addEventListener("keydown",v.throttle(d,500))}s.coverModal.addEventListener("click",o=>{(o.target.classList.contains("cover-modal")||o.target.classList.contains("modal-btn-close"))&&(s.coverModal.classList.remove("visible-element"),s.body.classList.remove("no-scroll"),document.removeEventListener("keydown",d))});function d(o){o.key==="Escape"&&(s.coverModal.classList.remove("visible-element"),document.removeEventListener("keydown",d))}function x(o){const e=u();e.some(n=>n._id===o._id)||(e.push(o),L(e)),m(o._id)}function u(){return JSON.parse(localStorage.getItem("booksInList"))??[]}function L(o){localStorage.setItem("booksInList",JSON.stringify(o))}function m(o){u().some(n=>n._id===o)?(s.addBtn.style.display="none",s.removeBtn.style.display="block",s.modalText.style.display="block"):(s.addBtn.style.display="block",s.removeBtn.style.display="none",s.modalText.style.display="none")}function T(o){const t=u().filter(n=>n._id!==o);L(t),m(o)}
//# sourceMappingURL=commonHelpers.js.map
